<?php

App::uses('AppController', 'Controller');

/**
 * Companytypes Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Companytype $Companytype
 * @property PaginatorComponent $Paginator
 */
class CompanytypesController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->Companytype->recursive = 0;
        $this->set('companytypes', $this->Paginator->paginate());
    }

    /**
     * view method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function view($id = null) {
        if (!$this->Companytype->exists($id)) {
            throw new NotFoundException(__('Invalid companytype'));
        }
        $options = array('conditions' => array('Companytype.' . $this->Companytype->primaryKey => $id));
        $this->set('companytype', $this->Companytype->find('first', $options));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Companytype->create();
            $this->request->data['Companytype']['entry_by'] = $this->Auth->user('id');
            if ($this->Companytype->save($this->request->data)) {
                $this->Flash->success(__('The companytype has been saved.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The companytype could not be saved. Please, try again.'));
            }
        }
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Companytype->exists($id)) {
            throw new NotFoundException(__('Invalid companytype'));
        }
        if ($this->request->is(array('post', 'put'))) {
            $this->request->data['Companytype']['edit_by'] = $this->Auth->user('id');
            if ($this->Companytype->save($this->request->data)) {
                $this->Flash->success(__('The companytype has been updated.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The companytype could not be updated. Please, try again.'));
            }
        } else {
            $options = array('conditions' => array('Companytype.' . $this->Companytype->primaryKey => $id));
            $this->request->data = $this->Companytype->find('first', $options);
        }
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Companytype->id = $id;
        if (!$this->Companytype->exists()) {
            throw new NotFoundException(__('Invalid companytype'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Companytype->delete()) {
            $this->Flash->success(__('The companytype has been deleted.'));
        } else {
            $this->Flash->error(__('The companytype could not be deleted. Please, try again.'));
        }
        return $this->redirect(array('action' => 'index'));
    }

}
