<?php

App::uses('AppController', 'Controller');

/**
 * Companynatures Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Companynature $Companynature
 * @property PaginatorComponent $Paginator
 */
class CompanynaturesController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->Companynature->recursive = 0;
        $this->set('companynatures', $this->Paginator->paginate());
    }

    /**
     * view method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function view($id = null) {
        if (!$this->Companynature->exists($id)) {
            throw new NotFoundException(__('Invalid companynature'));
        }
        $options = array('conditions' => array('Companynature.' . $this->Companynature->primaryKey => $id));
        $this->set('companynature', $this->Companynature->find('first', $options));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Companynature->create();
            $this->request->data['Companynature']['entry_by'] = $this->Auth->user('id');
            if ($this->Companynature->save($this->request->data)) {
                $this->Flash->success(__('The companynature has been saved.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The companynature could not be saved. Please, try again.'));
            }
        }
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Companynature->exists($id)) {
            throw new NotFoundException(__('Invalid companynature'));
        }
        if ($this->request->is(array('post', 'put'))) {
            $this->request->data['Companynature']['edit_by'] = $this->Auth->user('id');
            if ($this->Companynature->save($this->request->data)) {
                $this->Flash->success(__('The companynature has been updated.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The companynature could not be updated. Please, try again.'));
            }
        } else {
            $options = array('conditions' => array('Companynature.' . $this->Companynature->primaryKey => $id));
            $this->request->data = $this->Companynature->find('first', $options);
        }
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Companynature->id = $id;
        if (!$this->Companynature->exists()) {
            throw new NotFoundException(__('Invalid companynature'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Companynature->delete()) {
            $this->Flash->success(__('The companynature has been deleted.'));
        } else {
            $this->Flash->error(__('The companynature could not be deleted. Please, try again.'));
        }
        return $this->redirect(array('action' => 'index'));
    }

}
