<?php

App::uses('AppController', 'Controller');

/**
 * Sections Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Section $Section
 * @property PaginatorComponent $Paginator
 */
class SectionsController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->Section->recursive = 0;
        $conditions = array();
        if (!empty($this->request->data['Src']['company_id'])) {
            $conditions[] = array("Department.company_id " => $this->request->data['Src']['company_id']);
        }
        if (!empty($this->request->data['Src']['department_id'])) {
            $conditions[] = array("Section.department_id " => $this->request->data['Src']['department_id']);
        }
        if (!empty($this->request->data['Src']['name'])) {
            $conditions[] = array("Section.name LIKE '%" . $this->request->data['Src']['name'] . "%'");
        }
        $this->Paginator->settings = array('conditions' => $conditions, 'order' => array('Section.id' => 'DESC'));
        $this->set('sections', $this->Paginator->paginate());

        $companies = $this->Section->Department->Company->find('list', array('conditions' => array('status' => E_ERROR)));
        $this->set(compact('companies'));
    }

    /**
     * view method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function view($id = null) {
        if (!$this->Section->exists($id)) {
            throw new NotFoundException(__('Invalid section'));
        }
        $options = array('conditions' => array('Section.' . $this->Section->primaryKey => $id));
        $this->set('section', $this->Section->find('first', $options));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Section->create();
            if ($this->Section->save($this->request->data)) {
                $this->Flash->success(__('The section has been saved.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The section could not be saved. Please, try again.'));
            }
        }
        $companies = $this->Section->Department->Company->find('list', array('conditions' => array('status' => E_ERROR)));
        $this->set(compact('companies'));
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Section->exists($id)) {
            throw new NotFoundException(__('Invalid section'));
        }
        if ($this->request->is(array('post', 'put'))) {
            if ($this->Section->save($this->request->data)) {
                $this->Flash->success(__('The section has been updated.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The section could not be updated. Please, try again.'));
            }
        } else {
            $options = array('conditions' => array('Section.' . $this->Section->primaryKey => $id));
            $this->request->data = $this->Section->find('first', $options);
        }
        $companies = $this->Section->Department->Company->find('list', array('conditions' => array('status' => E_ERROR)));
        $this->set(compact('companies'));
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Section->id = $id;
        if (!$this->Section->exists()) {
            throw new NotFoundException(__('Invalid section'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Section->delete()) {
            $this->Flash->success(__('The section has been deleted.'));
        } else {
            $this->Flash->error(__('The section could not be deleted. Please, try again.'));
        }
        return $this->redirect(array('action' => 'index'));
    }

    public function ajax_getsections() {
        $this->layout = 'ajax';

        $sections = $this->Section->find('list', array('conditions' => array('department_id' => $this->request->data('department_id'))));
        $this->set('sections', $sections);
        $this->set('model', $this->request->data('model'));
        $this->set('section_id', $this->request->data('section_id'));
    }

}
