<?php

App::uses('AppController', 'Controller');

/**
 * Suppliers Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 *
 * @property Supplier $Supplier
 * @property PaginatorComponent $Paginator
 */
class SuppliersController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * http://www.softwareend.com
     * @return void
     */
    public function index() {
        $this->Supplier->recursive = 0;

        $conditions = array();
        if (!empty($this->request->data['Src']['id'])) {
            $conditions[] = array("Supplier.id" => $this->request->data['Src']['id']);
        }
        if (!empty($this->request->data['Src']['name'])) {
            $conditions[] = array("Supplier.name" => $this->request->data['Src']['name']);
        }
        if (!empty($this->request->data['Src']['created'])) {
            $conditions[] = array("Supplier.created" => "'" . $this->request->data['Src']['created'] . "'");
        }

        $this->Paginator->settings = array('conditions' => $conditions, 'order' => array('Supplier.created' => 'DESC'));
        $this->set('suppliers', $this->Paginator->paginate());
    }

    /**
     * view method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function view($id = null) {
        if (!$this->Supplier->exists($id)) {
            throw new NotFoundException(__('Invalid supplier'));
        }
        $options = array('conditions' => array('Supplier.' . $this->Supplier->primaryKey => $id));
        $this->set('supplier', $this->Supplier->find('first', $options));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Supplier->create();
            $this->request->data['Supplier']['entry_by'] = $this->Auth->user('id');
            if ($this->Supplier->save($this->request->data)) {
                $this->Flash->success(__('The supplier has been saved.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The supplier could not be saved. Please, try again.'));
            }
        }
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Supplier->exists($id)) {
            throw new NotFoundException(__('Invalid supplier'));
        }
        if ($this->request->is(array('post', 'put'))) {
            $this->request->data['Supplier']['edit_by'] = $this->Auth->user('id');
            if ($this->Supplier->save($this->request->data)) {
                $this->Flash->success(__('The supplier has been saved.'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error(__('The supplier could not be saved. Please, try again.'));
            }
        } else {
            $options = array('conditions' => array('Supplier.' . $this->Supplier->primaryKey => $id));
            $this->request->data = $this->Supplier->find('first', $options);
        }
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        if (!$this->Supplier->exists($id)) {
            throw new NotFoundException(__('Invalid supplier'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Supplier->delete($id)) {
            $this->Flash->success(__('The supplier has been deleted.'));
        } else {
            $this->Flash->error(__('The supplier could not be deleted. Please, try again.'));
        }
        return $this->redirect(array('action' => 'index'));
    }

}
